from pathlib import Path

import httpx2 as http
from httpx2 import HTTPStatusError
from rich.console import Console

from gignore.config import BASE_URL

console = Console()


async def request(uri: str) -> str:
    url = f"{BASE_URL}/{uri}"

    async with http.AsyncClient() as client:
        try:
            response = await client.get(url)
            response.raise_for_status()
            return response.text

        except HTTPStatusError as ex:
            console.print(
                f"[bold red]✗[/bold red] An error occurred while fetching "
                f"[yellow]{url}[/yellow]: {ex}"
            )
            return ""


async def get_data(flags: str) -> str:
    content = await request(flags)
    return content


async def get_templates() -> str:
    templates = await request("list") or ""
    return templates


async def find_templates(data: list[str]) -> list[str]:
    content = []
    response = await get_templates()
    if response is not None:
        templates = {template.strip() for template in data}
        content = [
            template.strip() for template in response.split(",") if template.strip() in templates
        ]

    return content


async def create_file(content: str, path: Path) -> bool:
    try:
        path.write_text(
            content + "\n# Generated by gignore\n" + "# https://github.com/ze-fernando/gignore\n",
            encoding="utf-8",
        )

        console.print(
            f"[bold green]✓[/bold green] .gitignore successfully created at [bold]{path}[/bold]"
        )
        return True
    except OSError as ex:
        console.print(f"[bold red]✗[/bold red] Could not create the .gitignore file\nError: {ex}")
        return False


async def edit_file(content: str, path: Path) -> bool:
    try:
        with path.open("a", encoding="utf-8") as file:
            file.write(
                content
                + "\n# Generated by gignore\n"
                + "# https://github.com/ze-fernando/gignore\n",
            )
        console.print(
            f"[bold green]✓[/bold green] .gitignore successfully created at [bold]{path}[/bold]"
        )
        return True
    except OSError as ex:
        console.print(f"[bold red]✗[/bold red] Could not create the .gitignore file\nError: {ex}")
        return False
