import asyncio
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from pathlib import Path

import httpx2 as http
from httpx2 import HTTPStatusError
from rich.console import Console

BASE_URL = "https://donotcommit.com/api"

console = Console()


async def request_content(flags: str) -> str | None:
    url = f"{BASE_URL}/{flags}"

    async with http.AsyncClient() as client:
        try:
            response = await client.get(url)
            response.raise_for_status()
            return response.text

        except HTTPStatusError as ex:
            console.print(
                f"[bold red]✗[/bold red] Não foi possível buscar [yellow]{flags}[/yellow]: {ex}"
            )
            return None


async def get_tempales() -> str | None:
    url = f"{BASE_URL}/list"

    async with http.AsyncClient() as client:
        try:
            response = await client.get(url)
            response.raise_for_status()

            print(response.text)
            return response.text

        except HTTPStatusError as ex:
            console.print(f"[bold red]✗[/bold red] Não foi possível buscar: {ex}")
            return None


async def find_templates(data: list[str]) -> str:
    url = f"{BASE_URL}/list"

    async with http.AsyncClient() as client:
        try:
            response = await client.get(url)
            response.raise_for_status()

            templates = {template.strip() for template in data}

            content = [
                template.strip()
                for template in response.text.split(",")
                if template.strip() in templates
            ]
            print(content)
            return response.text

        except HTTPStatusError as ex:
            console.print(f"[bold red]✗[/bold red] Não foi possível buscar: {ex}")
            return ""


async def main() -> None:
    parser = ArgumentParser(
        prog="gignore",
        description=("Gera um arquivo .gitignore baseado nos templates do gitignore.io."),
        epilog=(
            "Exemplos:\n"
            "  gignore python\n"
            "  gignore python,node\n\n"
            "[yellow]Aviso:[/yellow] se já existir um arquivo .gitignore "
            "no diretório atual, ele será sobrescrito."
        ),
        formatter_class=RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "ignore",
        help="Templates do .gitignore separados por vírgula. Ex: python,linux,vscode",
        nargs="?",
    )

    parser.add_argument(
        "-l", "--list", help="Lista os tempaltes do .gitignore disponíveis", action="store_true"
    )

    parser.add_argument("-f", "--find", help="Busca os tempaltes do .gitignore disponíveis")
    parser.add_argument(
        "-o", "--override", help="Força sobrescrita do .gitignore", action="store_true"
    )

    parser.add_argument("-p", "--path", help="Define a pasta do destino do arquivo")

    args = parser.parse_args()
    if args.list:
        await get_tempales()
    elif args.find:
        await find_templates(args.find.split(","))
    elif args.ignore:
        path = Path.cwd() / ".gitignore"
        if path.exists():
            if args.override:
                content = await request_content(args.ignore)

                if not content:
                    return

                    path.write_text(
                        content
                        + "\n# Generated by gignore\n"
                        + "# https://github.com/ze-fernando/gignore\n",
                        encoding="utf-8",
                    )

                    console.print(
                        f"[bold green]✓[/bold green] .gitignore criado com sucesso em [bold]{path}[/bold]"
                    )
            else:
                print("Coe po ja tem")
        else:
            path /= ".gitignore"

            content = await request_content(args.ignore)

            if not content:
                return

                path.write_text(
                    content
                    + "\n# Generated by gignore\n"
                    + "# https://github.com/ze-fernando/gignore\n",
                    encoding="utf-8",
                )

                console.print(
                    f"[bold green]✓[/bold green] .gitignore criado com sucesso em [bold]{path}[/bold]"
                )

    else:
        parser.error("informe um template ou use --list")

        console.print(f"[cyan]⟳[/cyan] Buscando templates: [bold]{args.ignore}[/bold]")


if __name__ == "__main__":
    asyncio.run(main())
