import asyncio
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from pathlib import Path

import httpx2 as http
from httpx2 import HTTPStatusError
from rich.console import Console

BASE_URL = "https://www.toptal.com/developers/gitignore/api"

console = Console()


async def request_content(flags: str) -> str | None:
    url = f"{BASE_URL}/{flags}"

    async with http.AsyncClient() as client:
        try:
            response = await client.get(url)
            response.raise_for_status()
            return response.text

        except HTTPStatusError as ex:
            console.print(
                f"[bold red]✗[/bold red] Não foi possível buscar [yellow]{flags}[/yellow]: {ex}"
            )
            return None


def main() -> None:
    parser = ArgumentParser(
        prog="gignore",
        description=("Gera um arquivo .gitignore baseado nos templates do gitignore.io."),
        epilog=(
            "Exemplos:\n"
            "  gignore python\n"
            "  gignore python,node\n\n"
            "[yellow]Aviso:[/yellow] se já existir um arquivo .gitignore "
            "no diretório atual, ele será sobrescrito."
        ),
        formatter_class=RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "ignore",
        help="Templates do .gitignore separados por vírgula. Ex: python,linux,vscode",
    )

    args = parser.parse_args()

    console.print(f"[cyan]⟳[/cyan] Buscando templates: [bold]{args.ignore}[/bold]")

    content = asyncio.run(request_content(args.ignore))

    if not content:
        return

    path = Path.cwd() / ".gitignore"

    path.write_text(
        content + "\n# Generated by gignore\n" + "# https://github.com/ze-fernando/gignore\n",
        encoding="utf-8",
    )

    console.print(
        f"[bold green]✓[/bold green] .gitignore criado com sucesso em [bold]{path}[/bold]"
    )


if __name__ == "__main__":
    main()
