name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/gignore-cli

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install Poetry
        run: pip install poetry

      - name: Build
        run: poetry build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
